<#
  build-tickers.ps1
  ------------------
  Downloads NASDAQ's public listed-company directories and bundles them
  into public/tickers.js — a static {symbol, name} list the search bar's
  dropdown filters locally, with no live API call needed just to search.

  Source: NASDAQ Trader SymDir (nasdaqlisted.txt + otherlisted.txt), which
  together cover all NASDAQ-, NYSE-, and NYSE American-listed securities,
  companies and ETFs alike (e.g. QQQ, SPY, IWM). Test issues are excluded.

  Re-run any time to refresh the list:
      powershell -File scripts/build-tickers.ps1
#>

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$outFile = Join-Path $root "public\tickers.js"
$headers = @{ "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36" }

Write-Host "Fetching NASDAQ-listed directory..."
$nasdaq = Invoke-RestMethod -Uri "https://www.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt" -Headers $headers -TimeoutSec 30
Write-Host "Fetching other-listed (NYSE/NYSE American/etc.) directory..."
$other = Invoke-RestMethod -Uri "https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt" -Headers $headers -TimeoutSec 30

$list = New-Object System.Collections.Generic.List[object]
$seen = @{}

function Add-Ticker($symbol, $name, $etf, $testIssue) {
    if (-not $symbol -or -not $name) { return }
    $symbol = $symbol.Trim()
    if ($symbol -eq "" -or $symbol -match "[\.\$]" -or $symbol.Length -gt 6) { return } # skip odd/derivative symbols
    if ($testIssue -eq "Y") { return }
    if ($seen.ContainsKey($symbol)) { return }
    $seen[$symbol] = $true
    # Trim common boilerplate suffixes so names stay compact in the dropdown.
    $clean = $name.Trim() -replace "\s*-\s*Common Stock.*$", "" -replace "\s*Common Stock$", ""
    $list.Add([PSCustomObject]@{ s = $symbol; n = $clean })
}

$nasdaqLines = ($nasdaq -split "`r?`n") | Where-Object { $_ -and $_ -notmatch "^File Creation Time" }
foreach ($line in ($nasdaqLines | Select-Object -Skip 1)) {
    $f = $line -split "\|"
    if ($f.Count -lt 6) { continue }
    Add-Ticker -symbol $f[0] -name $f[1] -etf $f[6] -testIssue $f[3]
}

$otherLines = ($other -split "`r?`n") | Where-Object { $_ -and $_ -notmatch "^File Creation Time" }
foreach ($line in ($otherLines | Select-Object -Skip 1)) {
    $f = $line -split "\|"
    if ($f.Count -lt 7) { continue }
    Add-Ticker -symbol $f[0] -name $f[1] -etf $f[4] -testIssue $f[6]
}

# NASDAQ's directories only cover stock-exchange-listed securities, so raw
# crypto pairs (as opposed to crypto ETFs like IBIT, which ARE listed and
# already included above) don't appear there at all. Yahoo Finance quotes
# them under a "<COIN>-USD" symbol, which api/history.js already fetches
# fine as-is - they just need to be hand-added here so they're searchable.
$cryptoPairs = @(
    @{ s = "BTC-USD"; n = "Bitcoin USD" },
    @{ s = "ETH-USD"; n = "Ethereum USD" },
    @{ s = "SOL-USD"; n = "Solana USD" },
    @{ s = "XRP-USD"; n = "XRP USD" },
    @{ s = "BNB-USD"; n = "BNB USD" },
    @{ s = "DOGE-USD"; n = "Dogecoin USD" },
    @{ s = "ADA-USD"; n = "Cardano USD" },
    @{ s = "TRX-USD"; n = "TRON USD" },
    @{ s = "AVAX-USD"; n = "Avalanche USD" },
    @{ s = "LINK-USD"; n = "Chainlink USD" },
    @{ s = "TON-USD"; n = "Toncoin USD" },
    @{ s = "SHIB-USD"; n = "Shiba Inu USD" },
    @{ s = "DOT-USD"; n = "Polkadot USD" },
    @{ s = "LTC-USD"; n = "Litecoin USD" },
    @{ s = "BCH-USD"; n = "Bitcoin Cash USD" },
    @{ s = "UNI-USD"; n = "Uniswap USD" },
    @{ s = "NEAR-USD"; n = "NEAR Protocol USD" },
    @{ s = "XLM-USD"; n = "Stellar USD" },
    @{ s = "ETC-USD"; n = "Ethereum Classic USD" },
    @{ s = "ATOM-USD"; n = "Cosmos USD" }
)
foreach ($c in $cryptoPairs) {
    if ($seen.ContainsKey($c.s)) { continue }
    $seen[$c.s] = $true
    $list.Add([PSCustomObject]@{ s = $c.s; n = $c.n })
}

$sorted = $list | Sort-Object s
Write-Host "Bundled $($sorted.Count) tickers."

$json = $sorted | ConvertTo-Json -Depth 3 -Compress
$js = "// Auto-generated by scripts/build-tickers.ps1 - do not edit by hand.`n"
$js += "// {s: symbol, n: company name} - static list for the search dropdown only.`n"
$js += "window.TICKER_LIST = $json;`n"
Set-Content -Path $outFile -Value $js -Encoding UTF8
Write-Host "Wrote $outFile"
