<#
  update-fed-policy.ps1
  ----------------------
  Downloads the monthly Effective Federal Funds Rate (FRED series FEDFUNDS,
  no API key needed for the CSV export endpoint) and classifies each
  calendar year into a Fed policy regime by comparing that year's first
  available month's rate to its last:

    "cut"    - end-of-year rate is more than 0.25pp LOWER than start-of-year
    "hike"   - end-of-year rate is more than 0.25pp HIGHER than start-of-year
    "stable" - within +/-0.25pp

  FEDFUNDS only goes back to mid-1954, so years before that simply have no
  entry here - the app's Fed Policy Regime filter naturally excludes them
  from every specific bucket (they still show up under "All").

  Output: public/fed-policy.js
      window.FED_POLICY_BY_YEAR = { "1970": "hike", "1971": "cut", ... };

  Re-run any time to refresh:
      powershell -File scripts/update-fed-policy.ps1

  If PowerShell's own HTTP client can't reach FRED from this machine (some
  environments proxy/block it while curl still works fine), fetch the CSV
  yourself and point -CsvPath at it instead:
      curl -s "https://fred.stlouisfed.org/graph/fredgraph.csv?id=FEDFUNDS" -o fedfunds.csv
      powershell -File scripts/update-fed-policy.ps1 -CsvPath fedfunds.csv
#>

param([string]$CsvPath = "")

$ErrorActionPreference = "Stop"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$root = Split-Path -Parent $PSScriptRoot
$outFile = Join-Path $root "public\fed-policy.js"
$headers = @{ "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36" }

if ($CsvPath) {
    Write-Host "Reading FEDFUNDS from local file: $CsvPath"
    $rows = Get-Content -Path $CsvPath -Raw | ConvertFrom-Csv
} else {
    Write-Host "Fetching FEDFUNDS (Effective Federal Funds Rate) from FRED..."
    $csv = Invoke-RestMethod -Uri "https://fred.stlouisfed.org/graph/fredgraph.csv?id=FEDFUNDS" -Headers $headers -TimeoutSec 60
    $rows = $csv | ConvertFrom-Csv
}
Write-Host "Received $($rows.Count) monthly observations."

# Group by year, keeping (month, rate) pairs in chronological order.
$byYear = @{}
foreach ($r in $rows) {
    $date = [datetime]$r.observation_date
    $rate = $r.FEDFUNDS
    if ($rate -eq "." -or [string]::IsNullOrWhiteSpace($rate)) { continue } # FRED uses "." for missing
    $y = $date.Year
    if (-not $byYear.ContainsKey($y)) { $byYear[$y] = New-Object System.Collections.Generic.List[object] }
    $byYear[$y].Add([PSCustomObject]@{ Month = $date.Month; Rate = [double]$rate })
}

$THRESHOLD = 0.25
$result = [ordered]@{}
$cutCount = 0; $hikeCount = 0; $stableCount = 0

foreach ($y in ($byYear.Keys | Sort-Object)) {
    $months = $byYear[$y] | Sort-Object Month
    if ($months.Count -lt 2) { continue } # need at least a start and end point
    $startRate = $months[0].Rate
    $endRate = $months[-1].Rate
    $diff = $endRate - $startRate

    if ($diff -lt -$THRESHOLD) { $regime = "cut"; $cutCount++ }
    elseif ($diff -gt $THRESHOLD) { $regime = "hike"; $hikeCount++ }
    else { $regime = "stable"; $stableCount++ }

    $result[[string]$y] = $regime
}

Write-Host "Classified $($result.Count) years - cuts: $cutCount, hikes: $hikeCount, stable: $stableCount"

$json = $result | ConvertTo-Json -Compress
$js = "// Auto-generated by scripts/update-fed-policy.ps1 - do not edit by hand.`n"
$js += "// {year: 'cut' | 'hike' | 'stable'} - years before FEDFUNDS coverage (mid-1954) are simply absent.`n"
$js += "window.FED_POLICY_BY_YEAR = $json;`n"

Set-Content -Path $outFile -Value $js -Encoding UTF8
Write-Host "Wrote $outFile"
